var player = {
    "name": "Rimuro",
    "speed": 2500,
    "sspeed": 0,
    "dmg": 1,
    "cspeed": 0,
    "magic": 1,
    "life": 10,
    "clife": 10,
    "regeneration": 0,
    "recovery": 1,
    "resistance": {},
    "chance": {},
    "effects": {},
    "counter": {},
    "skills": [],
    "status": {},
    "items": [],
    "maxitems": 1,
    "unlockeditems": [],
    "allcount": {},
    "time": 0,
    "auto": false,
    "lastEnemy": "bat",
    "version": 1.7,
    "highscore": {
        "vampire": -1,
        "hydra": -1,
        "iron_golem": -1,
        "chulthuluseye": -1,
        "necromant": -1,
        "chromeman": -1,
        "turret": -1,
        "jadis": -1
    },
    "tutorial": 0,
    "prestige": 0,
    "points": 0,
    "go": false,
    "order": [],
    "companion": null
}

export default player;